<li>
                             <h2>[field:title/]</h2>
                             <div class="news_show">
                                 <div class="text">
                                     <p>[field:description/]</p>
                                     <div class="content_wrap"></div>
                                 </div>
                                 <div class="text-center"><a href="[field:arcurl/]" class="show_btn">进入</a></div>
                             </div>
                        </li>