<li class="col-sm-12 col-md-6 col-lg-6">
                        <div class="row text-center"><img src="[field:picname/]" alt="" class="news-pic"></div>
                        <div class="pc-content">
                            <p>
                                鸡蛋一直有“全营养食品”的美称。
                                最新研究发现，宝宝一天吃一个鸡蛋，有助于避免
                                发育迟缓。
                            </p>
                        </div>
                        <div class="text-center"><span class="read-btn">查看更多</span></div>
                    </li>