<?php
$z[0]=Array("global","\r\n                                    if(@me==1) @me=class=\"col-sm-10\"\r\n                                    else if(@me==2) @me=class=\"col-sm-11 col-offset-1\"\r\n                                    else if(@me==3) @me=class=\"col-sm-11 col-offset-1\"\r\n                                    else if(@me==4) @me=class=\"col-sm-11 col-offset-1\"                         \r\n                                ",4,454);
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";

?>