<li [field:array name=autoindex runphp="yes"]
                                        if(@me==1) @me='class="col-sm-10"'
                                        else  @me='class="col-sm-10 col-offset-1" '                        
                                    [/field:array] >
                                    <div><img src="/templets/default/images/j1.png" alt=""></div>
                                </li>