<li>
                           <a href="[field:arcurl/]">
                               <div class="item">
                                   <div class="item-pic"><img src="[field:picname/]" alt=""></div>
                                   <div class="item-content">
                                       <h3 class="item-title cutout-text">[field:title/]</h3>
                                       <p class="item-text"> [field:description/] </p>
                                   </div>
                               </div>
                           </a>
                       </li>