<h4 class="section-title">今日推荐 --[field:title/]</h4>
                    <div class="row">
                        <div class="col-xs-24">
                                <div class="row">
                                    <div class="col-xs-24"><img src="/templets/default/images/j1.png" alt="" class="max-width"></div>
                                </div>
                            </div>
                            <div class="col-xs-24">
                                <div class="col-xs-24 col-md-12 mb-content">
                                    <p>[field:description/]</p>
                                    <div class="text-center"><a href="[field:arcurl/]" class="read-btn">查看更多</a></div>
                                </div>
                            </div>
                    </div>