<div class="col-xs-24 col-md-12 pc-content">
                                <h3 class="title">[field:title/]</h3>
                                <p>[field:description/]</p>
                                <div class="text-center"><a href="[field:arcurl/]" class="read-btn">查看更多</a></div>
                            </div>
                            <div class="col-xs-24 col-md-12 show-pic">
                                <div class="row">
                                    <div class="col-sm-10"><img src="/templets/default/images/j1.png" alt=""></div>
                                    <div class="col-sm-11 col-offset-1"><img src="/templets/default/images/j2.png" alt=""></div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12"><img src="/templets/default/images/j3.png" alt=""></div>
                                    <div class="col-sm-10 col-offset-1"><img src="/templets/default/images/j4.png" alt=""></div>
                                </div>                  
                            </div>