<li [field:array name=autoindex runphp="yes"]
                                        if(@me==1) @me=class="col-sm-10"
                                        else if(@me==2) @me="class=\"col-sm-11 col-offset-1\""
                                        else if(@me==3) @me=\"class="col-sm-12\""
                                        else if(@me==4) @me=\"class="col-sm-10 col-offset-1\""                         
                                    [/field:array] >
                                    <div><img src="/templets/default/images/j1.png" alt=""></div>
                                </li>