<?php
$z[0]=Array("include","",740,777);
$z[0][4]['filename']="header.htm";
$z[1]=Array("field","",918,947);
$z[1][4]['name']="position";
$z[2]=Array("field","",1112,1131);
$z[2][4]['name']="title";
$z[3]=Array("field","",1186,1242);
$z[3][4]['name']="pubdate";
$z[3][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[4]=Array("field","",1257,1277);
$z[4][4]['name']="writer";
$z[5]=Array("field","",1293,1313);
$z[5][4]['name']="source";
$z[6]=Array("field","",1343,1361);
$z[6][4]['name']="body";
$z[7]=Array("include","",1407,1447);
$z[7][4]['filename']="recommand.htm";
$z[8]=Array("include","",1509,1546);
$z[8][4]['filename']="footer.htm";

?>