<div class="col-xs-24 col-md-12 pc-content">
                                <h3 class="title">[field:title/]</h3>
                                <p>[field:description/]</p>
                                <div class="text-center"><a href="[field:arcurl/]" class="read-btn">查看更多</a></div>
                            </div>
                            <div class="col-xs-24 col-md-12 show-pic">
                                <div class="row">
                                    <div class="col-sm-24"><img src="[field:picname/]" alt=""></div>
                                </div>                 
                            </div>