<li class="col-sm-12 col-md-6 col-lg-6 pc-list-item">
                        <div class="row text-center">
                            <div class="inline-block news-pic">
                                <img src="[field:picname/]" alt="">
                                <p>[field:title/]</p>
                            </div>
                        </div>
                        <div class="text-center"><a href="[field:arcurl/]" class="read-btn">查看更多</a></div>
                    </li>