<li class="list-item">
                          <a href="[field:arcurl/]">
                            <div class="thumbnail"><img src="[field:picname/]" alt=""></div>
                            <div class="content-text">
                                <h3>[field:title/]</h3>
                                <p>[field:description/]</p>
                            </div>
                          </a>
                      </li>