<?php
$z[0]=Array("global","",390,415);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("channel","\r\n            <li><a href='[field:typeurl/]' [field:rel/]>[field:typename/]<span class=\"underline\"></span></a></li>\r\n            ",478,656);
$z[1][4]['type']="top";
$z[1][4]['row']="10";
$z[2]=Array("global","",1359,1384);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("type","<li><i class=\"icon anticon icon-profile\"></i><a href=\"[field:typelink /]\">[field:typename /]</a></li>",1411,1546);
$z[3][4]['typeid']="1";
$z[4]=Array("type","<li><i class=\"icon anticon icon-like1\"></i><a href=\"[field:typelink /]\">[field:typename /]</a></li>",1556,1689);
$z[4][4]['typeid']="2";
$z[5]=Array("type","<li><i class=\"icon anticon icon-book\"></i><a href=\"[field:typelink /]\">[field:typename /]</a></li>",1699,1831);
$z[5][4]['typeid']="3";
$z[6]=Array("type","<li><i class=\"icon anticon icon-star\"></i><a href=\"[field:typelink /]\">[field:typename /]</a></li>",1841,1973);
$z[6][4]['typeid']="4";
$z[7]=Array("type","<li><i class=\"icon anticon icon-heart\"></i><a href=\"[field:typelink /]\">[field:typename /]</a></li>",1983,2116);
$z[7][4]['typeid']="5";
$z[8]=Array("type","<li><i class=\"icon anticon icon-user\"></i><a href=\"[field:typelink /]\">[field:typename /]</a></li>",2142,2274);
$z[8][4]['typeid']="6";

?>