<?php
$z[0]=Array("include","",741,778);
$z[0][4]['filename']="header.htm";
$z[1]=Array("arclist","  \r\n                        <li class=\"col-xs-24 col-md-12 pc-content\">\r\n                            <h3 class=\"title\">[field:title/]</h3>\r\n                            <p>[field:description/]</p>\r\n                            <div class=\"text-center\">\r\n                                <a href=\"[field:arcurl/]\" class=\"read-btn\">查看更多</a>\r\n                            </div>\r\n                        </li>\r\n                        ",1080,1578);
$z[1][4]['row']="4";
$z[1][4]['orderby']="id";
$z[1][4]['typeid']="5";
$z[2]=Array("arclist","                          \r\n                                <li class=\"col-sm-10\">\r\n                                    <div><img src=\"[field:picname/]\" alt=\"\"></div>\r\n                                </li>\r\n                            ",1757,2054);
$z[2][4]['row']="4";
$z[2][4]['orderby']="id";
$z[2][4]['typeid']="5";
$z[3]=Array("arclist","  \r\n                            <li><a href=\"[field:arcurl/]\"><img _src=\"[field:picname/]\" src=\"[field:picname/]\" /></a></li>\r\n                            ",2502,2719);
$z[3][4]['row']="4";
$z[3][4]['orderby']="id";
$z[3][4]['typeid']="1";
$z[4]=Array("arclist","  \r\n                    <h4 class=\"section-title\">今日推荐 --[field:title/]</h4>\r\n                    <div class=\"row\">\r\n                        <div class=\"col-xs-24\">\r\n                                <div class=\"row\">\r\n                                    <div class=\"col-xs-24\"><img src=\"[field:picname/]\" alt=\"\" class=\"max-width\"></div>\r\n                                </div>\r\n                            </div>\r\n                            <div class=\"col-xs-24\">\r\n                                <div class=\"col-xs-24 col-md-12 mb-content\">\r\n                                    <p>[field:description/]</p>\r\n                                    <div class=\"text-center\"><a href=\"[field:arcurl/]\" class=\"read-btn\">查看更多</a></div>\r\n                                </div>\r\n                            </div>\r\n                    </div>\r\n                    ",3150,4081);
$z[4][4]['row']="1";
$z[4][4]['orderby']="id";
$z[4][4]['typeid']="5";
$z[5]=Array("arclist","                          \r\n                    <li class=\"col-sm-12 col-md-6 col-lg-6 pc-list-item\">\r\n                        <div class=\"row text-center\">\r\n                           <a href=\"[field:arcurl/]\">\r\n                                <div class=\"inline-block news-pic\">\r\n                                    <img src=\"[field:picname/]\" alt=\"\">\r\n                                    <p>[field:title/]</p>\r\n                                </div>\r\n                           </a>\r\n                        </div>\r\n                        <div class=\"text-center\"><a href=\"[field:arcurl/]\" class=\"read-btn\">查看更多</a></div>\r\n                    </li>\r\n                    ",4648,5392);
$z[5][4]['row']="4";
$z[5][4]['orderby']="id";
$z[5][4]['typeid']="4";
$z[6]=Array("arclist","  \r\n                       <li>\r\n                           <a href=\"[field:arcurl/]\">\r\n                               <div class=\"item\">\r\n                                   <div class=\"item-pic\"><img src=\"[field:picname/]\" alt=\"\"></div>\r\n                                   <div class=\"item-content\">\r\n                                       <h3 class=\"item-title cutout-text\">[field:title/]</h3>\r\n                                       <p class=\"item-text\"> [field:description/] </p>\r\n                                   </div>\r\n                               </div>\r\n                           </a>\r\n                       </li>\r\n                       ",5520,6235);
$z[6][4]['row']="4";
$z[6][4]['orderby']="id";
$z[6][4]['typeid']="4";
$z[7]=Array("include","",6341,6378);
$z[7][4]['filename']="footer.htm";

?>