<?php
$z[0]=Array("include","",733,770);
$z[0][4]['filename']="header.htm";
$z[1]=Array("field","",897,926);
$z[1][4]['name']="position";
$z[2]=Array("list","                                             \r\n                      <li class=\"list-item\">\r\n                          <a href=\"[field:arcurl/]\">\r\n                            <div class=\"thumbnail\"><img src=\"[field:picname/]\" alt=\"\"></div>\r\n                            <div class=\"content-text\">\r\n                                <h3>[field:title/]</h3>\r\n                                <p>[field:description/]</p>\r\n                            </div>\r\n                          </a>\r\n                      </li>\r\n                      ",1114,1697);
$z[2][4]['pagesize']="10";
$z[2][4]['orderway']="";
$z[3]=Array("pagelist","",1794,1865);
$z[3][4]['listitem']="info,index,end,pre,next,pageno";
$z[3][4]['listsize']="5";
$z[4]=Array("include","",1933,1973);
$z[4][4]['filename']="recommand.htm";
$z[5]=Array("include","",2019,2056);
$z[5][4]['filename']="footer.htm";

?>